# Jekyll configuration for dotfiles website

# Exclude directories that shouldn't be processed by Jekyll
exclude:
  - src/
  - tests/
  - .github/
  - .dotfiles.private/
  - styleguide/
  - Brewfile
  - Brewfile.lock.json
  - "*.sh"
  - .gitmodules
  - .gitignore

# Include only the directories needed for the website
include:
  - README.md
  - docs/
  - template/

# GitHub Pages settings
plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true