[font]
size = 18

[font.bold]
family = "MesloLGL Nerd Font"
style = "Bold"

[font.normal]
family = "MesloLGL Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[colors.primary]
background = '#161821'
foreground = '#c6c8d1'

[colors.normal]
black   = '#161821'
red     = '#e27878'
green   = '#b4be82'
yellow  = '#e2a478'
blue    = '#84a0c6'
magenta = '#a093c7'
cyan    = '#89b8c2'
white   = '#c6c8d1'

[colors.bright]
black   = '#6b7089'
red     = '#e27878'
green   = '#b4be82'
yellow  = '#e2a478'
blue    = '#84a0c6'
magenta = '#a093c7'
cyan    = '#89b8c2'
white   = '#d2d4de'
