-- GitHub Dark Tritanopia colorscheme for Neovim
-- Generated from colors.json - do not edit directly

local M = {}

-- Color palette
M.colors = {
  bg = "#0d1117",
  fg = "#c9d1d9",
  accent = "#58a6ff",
  border = "#30363d",
  surface = "#161b22",
  muted = "#8b949e",
  cursor = "#c9d1d9",
  selection = "#30363d",
  -- ANSI colors
  black = "#484f58",
  red = "#ff7b72",
  green = "#58a6ff",
  yellow = "#d29922",
  blue = "#58a6ff",
  magenta = "#bc8cff",
  cyan = "#39c5cf",
  white = "#b1bac4",
  -- Bright ANSI
  bright_black = "#6e7681",
  bright_red = "#ffa198",
  bright_green = "#79c0ff",
  bright_yellow = "#e3b341",
  bright_blue = "#79c0ff",
  bright_magenta = "#d2a8ff",
  bright_cyan = "#56d4dd",
  bright_white = "#ffffff",
}

function M.setup()
  local c = M.colors

  -- Reset all highlights
  vim.cmd("hi clear")
  if vim.fn.exists("syntax_on") then
    vim.cmd("syntax reset")
  end

  vim.g.colors_name = "github_dark_tritanopia"

  -- Editor highlights
  local highlights = {
    -- UI
    Normal = { fg = c.fg, bg = c.bg },
    NormalNC = { fg = c.fg, bg = c.bg },
    NormalSB = { fg = c.fg, bg = c.surface },
    NormalFloat = { fg = c.fg, bg = c.surface },
    FloatBorder = { fg = c.border, bg = c.surface },
    FloatTitle = { fg = c.accent, bg = c.surface },
    Cursor = { fg = c.bg, bg = c.cursor },
    lCursor = { fg = c.bg, bg = c.cursor },
    CursorIM = { fg = c.bg, bg = c.cursor },
    CursorLine = { bg = c.surface },
    CursorColumn = { bg = c.surface },
    ColorColumn = { bg = c.surface },
    LineNr = { fg = c.muted },
    LineNrAbove = { fg = c.muted },
    LineNrBelow = { fg = c.muted },
    CursorLineNr = { fg = c.accent, bold = true },
    SignColumn = { fg = c.muted, bg = c.bg },
    SignColumnSB = { fg = c.muted, bg = c.surface },
    VertSplit = { fg = c.border },
    WinSeparator = { fg = c.border, bold = true },
    Folded = { fg = c.blue, bg = c.surface },
    FoldColumn = { fg = c.muted, bg = c.bg },
    NonText = { fg = c.muted },
    SpecialKey = { fg = c.muted },
    Whitespace = { fg = c.muted },
    EndOfBuffer = { fg = c.bg },
    Conceal = { fg = c.muted },
    Directory = { fg = c.blue },
    Title = { fg = c.blue, bold = true },
    Bold = { bold = true },
    Italic = { italic = true },

    -- Popup menu
    Pmenu = { fg = c.fg, bg = c.surface },
    PmenuSel = { bg = c.selection },
    PmenuMatch = { fg = c.accent, bg = c.surface },
    PmenuMatchSel = { fg = c.accent, bg = c.selection },
    PmenuSbar = { bg = c.surface },
    PmenuThumb = { bg = c.muted },
    WildMenu = { bg = c.selection },

    -- Search
    Search = { fg = c.bg, bg = c.yellow },
    IncSearch = { fg = c.bg, bg = c.accent },
    CurSearch = { fg = c.bg, bg = c.accent },
    Substitute = { fg = c.bg, bg = c.red },
    MatchParen = { fg = c.yellow, bold = true },

    -- Visual
    Visual = { bg = c.selection },
    VisualNOS = { bg = c.selection },

    -- Messages
    ModeMsg = { fg = c.fg, bold = true },
    MsgArea = { fg = c.fg },
    MoreMsg = { fg = c.blue },
    Question = { fg = c.blue },
    WarningMsg = { fg = c.yellow },
    ErrorMsg = { fg = c.red },

    -- Quickfix
    QuickFixLine = { bg = c.selection, bold = true },
    qfFileName = { fg = c.blue },
    qfLineNr = { fg = c.muted },

    -- Status/Tab line
    StatusLine = { fg = c.fg, bg = c.surface },
    StatusLineNC = { fg = c.muted, bg = c.surface },
    StatusLineTerm = { fg = c.fg, bg = c.surface },
    StatusLineTermNC = { fg = c.muted, bg = c.surface },
    TabLine = { fg = c.fg, bg = c.surface },
    TabLineFill = { bg = c.surface },
    TabLineSel = { fg = c.accent, bg = c.bg, bold = true },
    WinBar = { fg = c.fg, bg = c.surface },
    WinBarNC = { fg = c.muted, bg = c.surface },

    -- Diff
    DiffAdd = { bg = c.surface },
    DiffChange = { bg = c.surface },
    DiffDelete = { bg = c.surface },
    DiffText = { bg = c.selection },
    diffAdded = { fg = c.green },
    diffRemoved = { fg = c.red },
    diffChanged = { fg = c.yellow },
    diffOldFile = { fg = c.yellow },
    diffNewFile = { fg = c.green },
    diffFile = { fg = c.blue },
    diffLine = { fg = c.muted },
    diffIndexLine = { fg = c.magenta },

    -- Spell
    SpellBad = { undercurl = true, sp = c.red },
    SpellCap = { undercurl = true, sp = c.yellow },
    SpellLocal = { undercurl = true, sp = c.cyan },
    SpellRare = { undercurl = true, sp = c.magenta },

    -- Diagnostics
    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticHint = { fg = c.cyan },
    DiagnosticUnnecessary = { fg = c.muted },
    DiagnosticVirtualTextError = { fg = c.red, bg = c.surface },
    DiagnosticVirtualTextWarn = { fg = c.yellow, bg = c.surface },
    DiagnosticVirtualTextInfo = { fg = c.blue, bg = c.surface },
    DiagnosticVirtualTextHint = { fg = c.cyan, bg = c.surface },
    DiagnosticUnderlineError = { undercurl = true, sp = c.red },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.blue },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.cyan },

    -- Health
    healthError = { fg = c.red },
    healthSuccess = { fg = c.green },
    healthWarning = { fg = c.yellow },

    -- Help
    helpCommand = { fg = c.blue, bg = c.surface },
    helpExample = { fg = c.muted },
    helpBacktick = { fg = c.cyan },

    -- HTML headers
    htmlH1 = { fg = c.magenta, bold = true },
    htmlH2 = { fg = c.blue, bold = true },

    -- Debug
    debugBreakpoint = { fg = c.blue, bg = c.surface },
    debugPC = { bg = c.surface },

    -- Syntax
    Comment = { fg = c.muted, italic = true },
    Constant = { fg = c.cyan },
    String = { fg = c.green },
    Character = { fg = c.green },
    Number = { fg = c.yellow },
    Boolean = { fg = c.yellow },
    Float = { fg = c.yellow },
    Identifier = { fg = c.fg },
    Function = { fg = c.blue },
    Statement = { fg = c.magenta },
    Conditional = { fg = c.magenta },
    Repeat = { fg = c.magenta },
    Label = { fg = c.magenta },
    Operator = { fg = c.fg },
    Keyword = { fg = c.magenta },
    Exception = { fg = c.magenta },
    PreProc = { fg = c.cyan },
    Include = { fg = c.magenta },
    Define = { fg = c.magenta },
    Macro = { fg = c.cyan },
    PreCondit = { fg = c.cyan },
    Type = { fg = c.yellow },
    StorageClass = { fg = c.yellow },
    Structure = { fg = c.yellow },
    Typedef = { fg = c.yellow },
    Special = { fg = c.cyan },
    SpecialChar = { fg = c.cyan },
    Tag = { fg = c.red },
    Delimiter = { fg = c.fg },
    SpecialComment = { fg = c.muted, italic = true },
    Debug = { fg = c.red },
    Underlined = { underline = true },
    Ignore = { fg = c.muted },
    Error = { fg = c.red },
    Todo = { fg = c.bg, bg = c.yellow, bold = true },

    -- Treesitter
    ["@annotation"] = { link = "PreProc" },
    ["@attribute"] = { link = "PreProc" },
    ["@boolean"] = { link = "Boolean" },
    ["@character"] = { link = "Character" },
    ["@character.printf"] = { link = "SpecialChar" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@comment"] = { link = "Comment" },
    ["@comment.error"] = { fg = c.red },
    ["@comment.hint"] = { fg = c.cyan },
    ["@comment.info"] = { fg = c.blue },
    ["@comment.note"] = { fg = c.cyan },
    ["@comment.todo"] = { fg = c.yellow },
    ["@comment.warning"] = { fg = c.yellow },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@constructor"] = { fg = c.magenta },
    ["@constructor.tsx"] = { fg = c.blue },
    ["@diff.delta"] = { link = "DiffChange" },
    ["@diff.minus"] = { link = "DiffDelete" },
    ["@diff.plus"] = { link = "DiffAdd" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "@function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "@function.method" },
    ["@keyword"] = { fg = c.magenta },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.coroutine"] = { link = "@keyword" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { fg = c.magenta },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { link = "Statement" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "@keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@label"] = { fg = c.blue },
    ["@markup"] = {},
    ["@markup.emphasis"] = { italic = true },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = c.cyan },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.link.label.symbol"] = { link = "Identifier" },
    ["@markup.link.url"] = { link = "Underlined" },
    ["@markup.list"] = { fg = c.blue },
    ["@markup.list.checked"] = { fg = c.green },
    ["@markup.list.markdown"] = { fg = c.yellow, bold = true },
    ["@markup.list.unchecked"] = { fg = c.blue },
    ["@markup.math"] = { link = "Special" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.raw.markdown_inline"] = { fg = c.blue, bg = c.surface },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    ["@module"] = { link = "Include" },
    ["@module.builtin"] = { fg = c.red },
    ["@namespace.builtin"] = { link = "@variable.builtin" },
    ["@none"] = {},
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@operator"] = { fg = c.fg },
    ["@property"] = { fg = c.green },
    ["@punctuation.bracket"] = { fg = c.fg },
    ["@punctuation.delimiter"] = { fg = c.fg },
    ["@punctuation.special"] = { fg = c.cyan },
    ["@punctuation.special.markdown"] = { fg = c.yellow },
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { fg = c.yellow },
    ["@string.escape"] = { fg = c.magenta },
    ["@string.regexp"] = { fg = c.blue },
    ["@string.special"] = { fg = c.cyan },
    ["@tag"] = { link = "Label" },
    ["@tag.attribute"] = { link = "@property" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@tag.delimiter.tsx"] = { fg = c.blue },
    ["@tag.tsx"] = { fg = c.red },
    ["@tag.javascript"] = { fg = c.red },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.cyan },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "@keyword" },
    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.red },
    ["@variable.member"] = { fg = c.green },
    ["@variable.parameter"] = { fg = c.yellow },
    ["@variable.parameter.builtin"] = { fg = c.yellow },
    -- Legacy treesitter captures
    ["@parameter"] = { fg = c.yellow },
    ["@method"] = { link = "Function" },
    ["@field"] = { fg = c.green },
    ["@namespace"] = { link = "@module" },
    ["@include"] = { link = "Include" },
    ["@preproc"] = { link = "PreProc" },
    ["@debug"] = { link = "Debug" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@exception"] = { link = "Exception" },
    ["@float"] = { link = "Float" },
    -- Legacy @text.* captures (for older treesitter configs)
    ["@text"] = { fg = c.fg },
    ["@text.strong"] = { bold = true },
    ["@text.emphasis"] = { italic = true },
    ["@text.underline"] = { underline = true },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { fg = c.green },
    ["@text.uri"] = { fg = c.blue, underline = true },
    ["@text.diff.add"] = { link = "DiffAdd" },
    ["@text.diff.delete"] = { link = "DiffDelete" },
    -- Additional treesitter captures
    ["@symbol"] = { fg = c.magenta },
    ["@parameter.reference"] = { fg = c.yellow },
    ["@string.special.url"] = { fg = c.blue, underline = true },

    -- LSP
    LspReferenceText = { bg = c.surface },
    LspReferenceRead = { bg = c.surface },
    LspReferenceWrite = { bg = c.surface },
    LspSignatureActiveParameter = { fg = c.accent },
    LspCodeLens = { fg = c.muted },
    LspInlayHint = { fg = c.muted, bg = c.surface },
    LspInfoBorder = { fg = c.border, bg = c.surface },

    -- Git signs
    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.yellow },
    GitSignsDelete = { fg = c.red },

    -- Telescope
    TelescopeNormal = { fg = c.fg, bg = c.bg },
    TelescopeBorder = { fg = c.border },
    TelescopePromptNormal = { fg = c.fg, bg = c.surface },
    TelescopePromptBorder = { fg = c.border, bg = c.surface },
    TelescopePromptTitle = { fg = c.bg, bg = c.accent },
    TelescopePreviewTitle = { fg = c.bg, bg = c.green },
    TelescopeResultsTitle = { fg = c.bg, bg = c.blue },
    TelescopeSelection = { fg = c.fg, bg = c.surface },
    TelescopeMatching = { fg = c.accent, bold = true },

    -- Which-key
    WhichKey = { fg = c.accent },
    WhichKeyGroup = { fg = c.blue },
    WhichKeyDesc = { fg = c.fg },
    WhichKeySeparator = { fg = c.muted },
    WhichKeyFloat = { bg = c.surface },
    WhichKeyNormal = { fg = c.fg, bg = c.surface },
    WhichKeyValue = { fg = c.muted },

    -- Indent guides
    IndentBlanklineChar = { fg = c.border },
    IndentBlanklineContextChar = { fg = c.accent },
    IblIndent = { fg = c.border },
    IblScope = { fg = c.accent },

    -- Bufferline (clean, minimal style - use fg for readability)
    BufferLineFill = { bg = c.surface },
    BufferLineBackground = { fg = c.fg, bg = c.surface },
    BufferLineBuffer = { fg = c.fg, bg = c.surface },
    BufferLineBufferSelected = { fg = c.accent, bg = c.bg, bold = true },
    BufferLineBufferVisible = { fg = c.fg, bg = c.surface },
    BufferLineIndicatorSelected = { fg = c.accent, bg = c.bg },
    BufferLineModified = { fg = c.green, bg = c.surface },
    BufferLineModifiedSelected = { fg = c.green, bg = c.bg },
    BufferLineModifiedVisible = { fg = c.green, bg = c.surface },
    BufferLineSeparator = { fg = c.surface, bg = c.surface },
    BufferLineSeparatorSelected = { fg = c.surface, bg = c.bg },
    BufferLineSeparatorVisible = { fg = c.surface, bg = c.surface },
    BufferLineCloseButton = { fg = c.muted, bg = c.surface },
    BufferLineCloseButtonSelected = { fg = c.muted, bg = c.bg },
    BufferLineCloseButtonVisible = { fg = c.muted, bg = c.surface },
    BufferLineTab = { fg = c.fg, bg = c.surface },
    BufferLineTabSelected = { fg = c.fg, bg = c.bg, bold = true },
    BufferLineTabClose = { fg = c.muted, bg = c.surface },
    BufferLineDuplicate = { fg = c.fg, bg = c.surface, italic = true },
    BufferLineDuplicateSelected = { fg = c.fg, bg = c.bg, italic = true },
    BufferLineDuplicateVisible = { fg = c.fg, bg = c.surface, italic = true },
    BufferLinePick = { fg = c.red, bg = c.surface, bold = true },
    BufferLinePickSelected = { fg = c.red, bg = c.bg, bold = true },
    BufferLinePickVisible = { fg = c.red, bg = c.surface, bold = true },
    BufferLineNumbers = { fg = c.fg, bg = c.surface },
    BufferLineNumbersSelected = { fg = c.fg, bg = c.bg },
    BufferLineNumbersVisible = { fg = c.fg, bg = c.surface },
    BufferLineDiagnostic = { fg = c.muted, bg = c.surface },
    BufferLineDiagnosticSelected = { fg = c.fg, bg = c.bg },
    BufferLineDiagnosticVisible = { fg = c.muted, bg = c.surface },
    BufferLineHint = { fg = c.cyan, bg = c.surface },
    BufferLineHintSelected = { fg = c.cyan, bg = c.bg },
    BufferLineHintVisible = { fg = c.cyan, bg = c.surface },
    BufferLineHintDiagnostic = { fg = c.cyan, bg = c.surface },
    BufferLineHintDiagnosticSelected = { fg = c.cyan, bg = c.bg },
    BufferLineInfo = { fg = c.blue, bg = c.surface },
    BufferLineInfoSelected = { fg = c.blue, bg = c.bg },
    BufferLineInfoVisible = { fg = c.blue, bg = c.surface },
    BufferLineInfoDiagnostic = { fg = c.blue, bg = c.surface },
    BufferLineInfoDiagnosticSelected = { fg = c.blue, bg = c.bg },
    BufferLineWarning = { fg = c.yellow, bg = c.surface },
    BufferLineWarningSelected = { fg = c.yellow, bg = c.bg },
    BufferLineWarningVisible = { fg = c.yellow, bg = c.surface },
    BufferLineWarningDiagnostic = { fg = c.yellow, bg = c.surface },
    BufferLineWarningDiagnosticSelected = { fg = c.yellow, bg = c.bg },
    BufferLineError = { fg = c.red, bg = c.surface },
    BufferLineErrorSelected = { fg = c.red, bg = c.bg },
    BufferLineErrorVisible = { fg = c.red, bg = c.surface },
    BufferLineErrorDiagnostic = { fg = c.red, bg = c.surface },
    BufferLineErrorDiagnosticSelected = { fg = c.red, bg = c.bg },
    BufferLineOffsetSeparator = { fg = c.surface, bg = c.surface },
    BufferLineTruncMarker = { fg = c.muted, bg = c.surface },

    -- DevIcon highlights for consistent bufferline icon backgrounds
    BufferLineDevIconDefault = { bg = c.surface },
    BufferLineDevIconDefaultSelected = { bg = c.bg },
    BufferLineDevIconDefaultInactive = { bg = c.surface },
    BufferLineDevIconLua = { fg = c.blue, bg = c.surface },
    BufferLineDevIconLuaSelected = { fg = c.blue, bg = c.bg },
    BufferLineDevIconLuaInactive = { fg = c.blue, bg = c.surface },
    BufferLineDevIconPy = { fg = c.yellow, bg = c.surface },
    BufferLineDevIconPySelected = { fg = c.yellow, bg = c.bg },
    BufferLineDevIconPyInactive = { fg = c.yellow, bg = c.surface },
    BufferLineDevIconJs = { fg = c.yellow, bg = c.surface },
    BufferLineDevIconJsSelected = { fg = c.yellow, bg = c.bg },
    BufferLineDevIconJsInactive = { fg = c.yellow, bg = c.surface },
    BufferLineDevIconTs = { fg = c.blue, bg = c.surface },
    BufferLineDevIconTsSelected = { fg = c.blue, bg = c.bg },
    BufferLineDevIconTsInactive = { fg = c.blue, bg = c.surface },
    BufferLineDevIconJson = { fg = c.yellow, bg = c.surface },
    BufferLineDevIconJsonSelected = { fg = c.yellow, bg = c.bg },
    BufferLineDevIconJsonInactive = { fg = c.yellow, bg = c.surface },
    BufferLineDevIconMd = { fg = c.blue, bg = c.surface },
    BufferLineDevIconMdSelected = { fg = c.blue, bg = c.bg },
    BufferLineDevIconMdInactive = { fg = c.blue, bg = c.surface },
    BufferLineDevIconSh = { fg = c.green, bg = c.surface },
    BufferLineDevIconShSelected = { fg = c.green, bg = c.bg },
    BufferLineDevIconShInactive = { fg = c.green, bg = c.surface },
    BufferLineDevIconZsh = { fg = c.green, bg = c.surface },
    BufferLineDevIconZshSelected = { fg = c.green, bg = c.bg },
    BufferLineDevIconZshInactive = { fg = c.green, bg = c.surface },
    BufferLineDevIconVim = { fg = c.green, bg = c.surface },
    BufferLineDevIconVimSelected = { fg = c.green, bg = c.bg },
    BufferLineDevIconVimInactive = { fg = c.green, bg = c.surface },
    BufferLineDevIconToml = { fg = c.red, bg = c.surface },
    BufferLineDevIconTomlSelected = { fg = c.red, bg = c.bg },
    BufferLineDevIconTomlInactive = { fg = c.red, bg = c.surface },
    BufferLineDevIconYaml = { fg = c.red, bg = c.surface },
    BufferLineDevIconYamlSelected = { fg = c.red, bg = c.bg },
    BufferLineDevIconYamlInactive = { fg = c.red, bg = c.surface },
    BufferLineDevIconYml = { fg = c.red, bg = c.surface },
    BufferLineDevIconYmlSelected = { fg = c.red, bg = c.bg },
    BufferLineDevIconYmlInactive = { fg = c.red, bg = c.surface },
    BufferLineDevIconGit = { fg = c.red, bg = c.surface },
    BufferLineDevIconGitSelected = { fg = c.red, bg = c.bg },
    BufferLineDevIconGitInactive = { fg = c.red, bg = c.surface },
    BufferLineDevIconRust = { fg = c.red, bg = c.surface },
    BufferLineDevIconRustSelected = { fg = c.red, bg = c.bg },
    BufferLineDevIconRustInactive = { fg = c.red, bg = c.surface },
    BufferLineDevIconGo = { fg = c.cyan, bg = c.surface },
    BufferLineDevIconGoSelected = { fg = c.cyan, bg = c.bg },
    BufferLineDevIconGoInactive = { fg = c.cyan, bg = c.surface },
    BufferLineDevIconC = { fg = c.blue, bg = c.surface },
    BufferLineDevIconCSelected = { fg = c.blue, bg = c.bg },
    BufferLineDevIconCInactive = { fg = c.blue, bg = c.surface },
    BufferLineDevIconCpp = { fg = c.blue, bg = c.surface },
    BufferLineDevIconCppSelected = { fg = c.blue, bg = c.bg },
    BufferLineDevIconCppInactive = { fg = c.blue, bg = c.surface },
    BufferLineDevIconH = { fg = c.magenta, bg = c.surface },
    BufferLineDevIconHSelected = { fg = c.magenta, bg = c.bg },
    BufferLineDevIconHInactive = { fg = c.magenta, bg = c.surface },
    BufferLineDevIconHpp = { fg = c.magenta, bg = c.surface },
    BufferLineDevIconHppSelected = { fg = c.magenta, bg = c.bg },
    BufferLineDevIconHppInactive = { fg = c.magenta, bg = c.surface },
    BufferLineDevIconHtml = { fg = c.red, bg = c.surface },
    BufferLineDevIconHtmlSelected = { fg = c.red, bg = c.bg },
    BufferLineDevIconHtmlInactive = { fg = c.red, bg = c.surface },
    BufferLineDevIconCss = { fg = c.blue, bg = c.surface },
    BufferLineDevIconCssSelected = { fg = c.blue, bg = c.bg },
    BufferLineDevIconCssInactive = { fg = c.blue, bg = c.surface },
    BufferLineDevIconScss = { fg = c.magenta, bg = c.surface },
    BufferLineDevIconScssSelected = { fg = c.magenta, bg = c.bg },
    BufferLineDevIconScssInactive = { fg = c.magenta, bg = c.surface },
    BufferLineDevIconTsx = { fg = c.blue, bg = c.surface },
    BufferLineDevIconTsxSelected = { fg = c.blue, bg = c.bg },
    BufferLineDevIconTsxInactive = { fg = c.blue, bg = c.surface },
    BufferLineDevIconJsx = { fg = c.blue, bg = c.surface },
    BufferLineDevIconJsxSelected = { fg = c.blue, bg = c.bg },
    BufferLineDevIconJsxInactive = { fg = c.blue, bg = c.surface },
    BufferLineDevIconRb = { fg = c.red, bg = c.surface },
    BufferLineDevIconRbSelected = { fg = c.red, bg = c.bg },
    BufferLineDevIconRbInactive = { fg = c.red, bg = c.surface },
    BufferLineDevIconPhp = { fg = c.magenta, bg = c.surface },
    BufferLineDevIconPhpSelected = { fg = c.magenta, bg = c.bg },
    BufferLineDevIconPhpInactive = { fg = c.magenta, bg = c.surface },
    BufferLineDevIconJava = { fg = c.red, bg = c.surface },
    BufferLineDevIconJavaSelected = { fg = c.red, bg = c.bg },
    BufferLineDevIconJavaInactive = { fg = c.red, bg = c.surface },
    BufferLineDevIconSql = { fg = c.yellow, bg = c.surface },
    BufferLineDevIconSqlSelected = { fg = c.yellow, bg = c.bg },
    BufferLineDevIconSqlInactive = { fg = c.yellow, bg = c.surface },
    BufferLineDevIconGraphql = { fg = c.magenta, bg = c.surface },
    BufferLineDevIconGraphqlSelected = { fg = c.magenta, bg = c.bg },
    BufferLineDevIconGraphqlInactive = { fg = c.magenta, bg = c.surface },
    BufferLineDevIconDocker = { fg = c.blue, bg = c.surface },
    BufferLineDevIconDockerSelected = { fg = c.blue, bg = c.bg },
    BufferLineDevIconDockerInactive = { fg = c.blue, bg = c.surface },
    BufferLineDevIconTxt = { fg = c.fg, bg = c.surface },
    BufferLineDevIconTxtSelected = { fg = c.fg, bg = c.bg },
    BufferLineDevIconTxtInactive = { fg = c.fg, bg = c.surface },

    -- Nvim-tree
    NvimTreeNormal = { fg = c.fg, bg = c.bg },
    NvimTreeFolderIcon = { fg = c.blue },
    NvimTreeFolderName = { fg = c.fg },
    NvimTreeOpenedFolderName = { fg = c.accent },
    NvimTreeRootFolder = { fg = c.accent, bold = true },
    NvimTreeGitDirty = { fg = c.yellow },
    NvimTreeGitNew = { fg = c.green },
    NvimTreeGitDeleted = { fg = c.red },
    NvimTreeSpecialFile = { fg = c.cyan },
    NvimTreeIndentMarker = { fg = c.border },
    NvimTreeNormalNC = { fg = c.fg, bg = c.bg },
    NvimTreeImageFile = { fg = c.magenta },
    NvimTreeOpenedFile = { fg = c.accent },
    NvimTreeSymlink = { fg = c.cyan },
    NvimTreeWinSeparator = { fg = c.border },

    -- Notify
    NotifyERRORBorder = { fg = c.red },
    NotifyERRORIcon = { fg = c.red },
    NotifyERRORTitle = { fg = c.red },
    NotifyWARNBorder = { fg = c.yellow },
    NotifyWARNIcon = { fg = c.yellow },
    NotifyWARNTitle = { fg = c.yellow },
    NotifyINFOBorder = { fg = c.blue },
    NotifyINFOIcon = { fg = c.blue },
    NotifyINFOTitle = { fg = c.blue },

    -- Lazy
    LazyButton = { fg = c.fg, bg = c.surface },
    LazyButtonActive = { fg = c.bg, bg = c.accent },
    LazyH1 = { fg = c.bg, bg = c.accent, bold = true },
    LazySpecial = { fg = c.cyan },

    -- Mini.statusline (statusline plugin)
    MiniStatuslineModeNormal = { fg = c.bg, bg = c.blue, bold = true },
    MiniStatuslineModeInsert = { fg = c.bg, bg = c.green, bold = true },
    MiniStatuslineModeVisual = { fg = c.bg, bg = c.magenta, bold = true },
    MiniStatuslineModeReplace = { fg = c.bg, bg = c.red, bold = true },
    MiniStatuslineModeCommand = { fg = c.bg, bg = c.yellow, bold = true },
    MiniStatuslineModeOther = { fg = c.bg, bg = c.cyan, bold = true },
    MiniStatuslineDevinfo = { fg = c.fg, bg = c.surface },
    MiniStatuslineFilename = { fg = c.fg, bg = c.surface },
    MiniStatuslineFileinfo = { fg = c.fg, bg = c.surface },
    MiniStatuslineInactive = { fg = c.muted, bg = c.surface },

    -- Aerial (code outline)
    AerialLine = { bg = c.surface },
    AerialLineNC = { bg = c.surface },
    AerialNormal = { fg = c.fg, bg = c.bg },
    AerialGuide = { fg = c.border },
    AerialGuide1 = { fg = c.border },
    AerialGuide2 = { fg = c.border },
    AerialClass = { fg = c.yellow },
    AerialClassIcon = { fg = c.yellow },
    AerialFunction = { fg = c.blue },
    AerialFunctionIcon = { fg = c.blue },
    AerialMethod = { fg = c.blue },
    AerialMethodIcon = { fg = c.blue },
    AerialField = { fg = c.cyan },
    AerialFieldIcon = { fg = c.cyan },
    AerialConstructor = { fg = c.yellow },
    AerialConstructorIcon = { fg = c.yellow },
    AerialEnum = { fg = c.yellow },
    AerialEnumIcon = { fg = c.yellow },
    AerialEnumMember = { fg = c.cyan },
    AerialEnumMemberIcon = { fg = c.cyan },
    AerialInterface = { fg = c.yellow },
    AerialInterfaceIcon = { fg = c.yellow },
    AerialModule = { fg = c.blue },
    AerialModuleIcon = { fg = c.blue },
    AerialNamespace = { fg = c.fg },
    AerialNamespaceIcon = { fg = c.fg },
    AerialPackage = { fg = c.cyan },
    AerialPackageIcon = { fg = c.cyan },
    AerialProperty = { fg = c.cyan },
    AerialPropertyIcon = { fg = c.cyan },
    AerialString = { fg = c.green },
    AerialStringIcon = { fg = c.green },
    AerialStruct = { fg = c.yellow },
    AerialStructIcon = { fg = c.yellow },
    AerialTypeParameter = { fg = c.yellow },
    AerialTypeParameterIcon = { fg = c.yellow },
    AerialVariable = { fg = c.fg },
    AerialVariableIcon = { fg = c.fg },

    -- Mini.indentscope
    MiniIndentscopeSymbol = { fg = c.accent },
    MiniIndentscopePrefix = { nocombine = true },

    -- Mini.pick
    MiniPickBorder = { fg = c.border, bg = c.surface },
    MiniPickBorderBusy = { fg = c.yellow, bg = c.surface },
    MiniPickBorderText = { fg = c.accent, bg = c.surface },
    MiniPickIconDirectory = { fg = c.blue },
    MiniPickIconFile = { fg = c.fg },
    MiniPickHeader = { fg = c.accent },
    MiniPickMatchCurrent = { bg = c.selection },
    MiniPickMatchMarked = { bg = c.surface, bold = true },
    MiniPickMatchRanges = { fg = c.accent, bold = true },
    MiniPickNormal = { fg = c.fg, bg = c.surface },
    MiniPickPreviewLine = { bg = c.surface },
    MiniPickPreviewRegion = { bg = c.selection },
    MiniPickPrompt = { fg = c.accent, bg = c.surface },

    -- Mini.surround
    MiniSurround = { fg = c.bg, bg = c.yellow },

    -- Mini.cursorword
    MiniCursorword = { bg = c.surface },
    MiniCursorwordCurrent = { bg = c.surface },

    -- Mini.jump
    MiniJump = { fg = c.bg, bg = c.accent, bold = true },
    MiniJump2dSpot = { fg = c.accent, bold = true, nocombine = true },
    MiniJump2dSpotAhead = { fg = c.accent, bg = c.surface, nocombine = true },
    MiniJump2dSpotUnique = { fg = c.yellow, bold = true, nocombine = true },

    -- Mini.files
    MiniFilesFile = { fg = c.fg },
    MiniFilesDirectory = { fg = c.blue },
    MiniFilesCursorLine = { bg = c.surface },
    MiniFilesNormal = { fg = c.fg, bg = c.bg },
    MiniFilesBorder = { fg = c.border },
    MiniFilesBorderModified = { fg = c.yellow },
    MiniFilesTitle = { fg = c.accent, bold = true },
    MiniFilesTitleFocused = { fg = c.accent, bold = true },

    -- Mini.diff
    MiniDiffSignAdd = { fg = c.green },
    MiniDiffSignChange = { fg = c.yellow },
    MiniDiffSignDelete = { fg = c.red },
    MiniDiffOverAdd = { bg = c.green },
    MiniDiffOverChange = { bg = c.yellow },
    MiniDiffOverContext = { bg = c.surface },
    MiniDiffOverDelete = { bg = c.red },

    -- Mini.hipatterns
    MiniHipatternsFixme = { fg = c.bg, bg = c.red, bold = true },
    MiniHipatternsHack = { fg = c.bg, bg = c.yellow, bold = true },
    MiniHipatternsNote = { fg = c.bg, bg = c.cyan, bold = true },
    MiniHipatternsTodo = { fg = c.bg, bg = c.accent, bold = true },

    -- Mini.icons
    MiniIconsAzure = { fg = c.blue },
    MiniIconsBlue = { fg = c.blue },
    MiniIconsCyan = { fg = c.cyan },
    MiniIconsGreen = { fg = c.green },
    MiniIconsGrey = { fg = c.muted },
    MiniIconsOrange = { fg = c.yellow },
    MiniIconsPurple = { fg = c.magenta },
    MiniIconsRed = { fg = c.red },
    MiniIconsYellow = { fg = c.yellow },

    -- Snacks.nvim
    SnacksNormal = { fg = c.fg, bg = c.bg },
    SnacksWinBar = { fg = c.fg, bg = c.bg },
    SnacksWinBarNC = { fg = c.muted, bg = c.bg },
    SnacksBackdrop = { bg = c.bg },
    SnacksIndent = { fg = c.border },
    SnacksIndentScope = { fg = c.accent },
    SnacksIndentChunk = { fg = c.accent },
    SnacksDashboardNormal = { fg = c.fg, bg = c.bg },
    SnacksDashboardDesc = { fg = c.fg },
    SnacksDashboardFile = { fg = c.fg },
    SnacksDashboardDir = { fg = c.muted },
    SnacksDashboardFooter = { fg = c.muted },
    SnacksDashboardHeader = { fg = c.accent },
    SnacksDashboardIcon = { fg = c.accent },
    SnacksDashboardKey = { fg = c.yellow },
    SnacksDashboardSpecial = { fg = c.cyan },
    SnacksDashboardTitle = { fg = c.accent, bold = true },
    SnacksNotifierInfo = { fg = c.blue },
    SnacksNotifierWarn = { fg = c.yellow },
    SnacksNotifierError = { fg = c.red },
    SnacksNotifierDebug = { fg = c.muted },
    SnacksNotifierTrace = { fg = c.magenta },
    SnacksNotifierIconInfo = { fg = c.blue },
    SnacksNotifierIconWarn = { fg = c.yellow },
    SnacksNotifierIconError = { fg = c.red },
    SnacksNotifierIconDebug = { fg = c.muted },
    SnacksNotifierIconTrace = { fg = c.magenta },

    -- Snacks.picker / explorer
    SnacksPickerDir = { fg = c.blue, bold = true },
    SnacksPickerFile = { fg = c.fg },
    SnacksPickerDirectory = { fg = c.blue },
    SnacksPickerPathIgnored = { fg = c.muted },
    SnacksPickerPathHidden = { fg = c.muted },
    SnacksPickerTree = { fg = c.border },
    SnacksPickerGitStatusAdded = { fg = c.green },
    SnacksPickerGitStatusModified = { fg = c.yellow },
    SnacksPickerGitStatusDeleted = { fg = c.red },
    SnacksPickerGitStatusRenamed = { fg = c.cyan },
    SnacksPickerGitStatusUntracked = { fg = c.cyan },
    SnacksPickerGitStatusStaged = { fg = c.green },
    SnacksPickerGitStatusIgnored = { fg = c.muted },
    SnacksPickerSelected = { fg = c.accent, bold = true },
    SnacksPickerMatch = { fg = c.accent, bold = true },
    SnacksPickerPrompt = { fg = c.accent },
    SnacksPickerCursorLine = { bg = c.surface },
    SnacksPickerNormal = { fg = c.fg, bg = c.bg },
    SnacksPickerNormalFloat = { fg = c.fg, bg = c.surface },
    SnacksPickerBorder = { fg = c.border, bg = c.bg },
    SnacksPickerFloatBorder = { fg = c.border, bg = c.surface },
    SnacksPickerFloatTitle = { fg = c.accent, bg = c.surface, bold = true },
    SnacksPickerFloatFooter = { fg = c.muted, bg = c.surface },
    SnacksPickerPreview = { fg = c.fg, bg = c.bg },
    SnacksPickerPreviewBorder = { fg = c.border, bg = c.bg },
    SnacksPickerPreviewTitle = { fg = c.accent, bg = c.bg, bold = true },
    SnacksPickerInput = { fg = c.fg, bg = c.surface },
    SnacksPickerInputBorder = { fg = c.accent, bg = c.surface },
    SnacksPickerInputTitle = { fg = c.accent, bg = c.surface, bold = true },
    SnacksPickerList = { fg = c.fg, bg = c.bg },
    SnacksPickerListBorder = { fg = c.border, bg = c.bg },
    SnacksPickerListTitle = { fg = c.accent, bg = c.bg, bold = true },
    SnacksPickerRow = { fg = c.muted },
    SnacksPickerVirtText = { fg = c.muted },
    SnacksPickerDelim = { fg = c.muted },
    SnacksPickerSpecial = { fg = c.cyan },
    SnacksPickerToggle = { fg = c.yellow },
    SnacksPickerIconFile = { fg = c.fg },
    SnacksPickerIconDirectory = { fg = c.blue },

    -- Blink.cmp (completion)
    BlinkCmpMenu = { fg = c.fg, bg = c.surface },
    BlinkCmpMenuBorder = { fg = c.border, bg = c.surface },
    BlinkCmpMenuSelection = { bg = c.selection },
    BlinkCmpLabel = { fg = c.fg },
    BlinkCmpLabelDeprecated = { fg = c.muted, strikethrough = true },
    BlinkCmpLabelMatch = { fg = c.accent, bold = true },
    BlinkCmpKind = { fg = c.accent },
    BlinkCmpKindClass = { fg = c.yellow },
    BlinkCmpKindColor = { fg = c.green },
    BlinkCmpKindConstant = { fg = c.cyan },
    BlinkCmpKindConstructor = { fg = c.yellow },
    BlinkCmpKindEnum = { fg = c.yellow },
    BlinkCmpKindEnumMember = { fg = c.cyan },
    BlinkCmpKindEvent = { fg = c.magenta },
    BlinkCmpKindField = { fg = c.cyan },
    BlinkCmpKindFile = { fg = c.fg },
    BlinkCmpKindFolder = { fg = c.blue },
    BlinkCmpKindFunction = { fg = c.blue },
    BlinkCmpKindInterface = { fg = c.yellow },
    BlinkCmpKindKeyword = { fg = c.magenta },
    BlinkCmpKindMethod = { fg = c.blue },
    BlinkCmpKindModule = { fg = c.blue },
    BlinkCmpKindOperator = { fg = c.fg },
    BlinkCmpKindProperty = { fg = c.cyan },
    BlinkCmpKindReference = { fg = c.cyan },
    BlinkCmpKindSnippet = { fg = c.green },
    BlinkCmpKindStruct = { fg = c.yellow },
    BlinkCmpKindText = { fg = c.fg },
    BlinkCmpKindTypeParameter = { fg = c.yellow },
    BlinkCmpKindUnit = { fg = c.yellow },
    BlinkCmpKindValue = { fg = c.cyan },
    BlinkCmpKindVariable = { fg = c.fg },
    BlinkCmpDoc = { fg = c.fg, bg = c.surface },
    BlinkCmpDocBorder = { fg = c.border, bg = c.surface },
    BlinkCmpDocSeparator = { fg = c.border },
    BlinkCmpSignatureHelp = { fg = c.fg, bg = c.surface },
    BlinkCmpSignatureHelpBorder = { fg = c.border, bg = c.surface },
    BlinkCmpGhostText = { fg = c.muted },

    -- Flash.nvim
    FlashBackdrop = { fg = c.muted },
    FlashMatch = { fg = c.fg, bg = c.selection },
    FlashCurrent = { fg = c.bg, bg = c.accent },
    FlashLabel = { fg = c.bg, bg = c.magenta, bold = true },
    FlashPrompt = { fg = c.fg, bg = c.surface },
    FlashPromptIcon = { fg = c.accent },
    FlashCursor = { reverse = true },

    -- Noice.nvim
    NoiceCmdline = { fg = c.fg },
    NoiceCmdlineIcon = { fg = c.accent },
    NoiceCmdlineIconSearch = { fg = c.yellow },
    NoiceCmdlinePopup = { fg = c.fg, bg = c.surface },
    NoiceCmdlinePopupBorder = { fg = c.border },
    NoiceCmdlinePopupTitle = { fg = c.accent },
    NoiceConfirm = { fg = c.fg, bg = c.surface },
    NoiceConfirmBorder = { fg = c.border },
    NoiceCursor = { fg = c.bg, bg = c.fg },
    NoiceMini = { fg = c.fg, bg = c.surface },
    NoicePopup = { fg = c.fg, bg = c.surface },
    NoicePopupBorder = { fg = c.border },
    NoicePopupmenu = { fg = c.fg, bg = c.surface },
    NoicePopupmenuBorder = { fg = c.border },
    NoicePopupmenuMatch = { fg = c.accent, bold = true },
    NoicePopupmenuSelected = { bg = c.selection },
    NoiceScrollbar = { fg = c.muted, bg = c.surface },
    NoiceScrollbarThumb = { bg = c.muted },
    NoiceSplit = { fg = c.fg, bg = c.bg },
    NoiceSplitBorder = { fg = c.border },
    NoiceVirtualText = { fg = c.muted },

    -- Mason.nvim
    MasonHeader = { fg = c.bg, bg = c.accent, bold = true },
    MasonHeaderSecondary = { fg = c.bg, bg = c.blue, bold = true },
    MasonHighlight = { fg = c.accent },
    MasonHighlightBlock = { fg = c.bg, bg = c.accent },
    MasonHighlightBlockBold = { fg = c.bg, bg = c.accent, bold = true },
    MasonHighlightBlockBoldSecondary = { fg = c.bg, bg = c.blue, bold = true },
    MasonHighlightBlockSecondary = { fg = c.bg, bg = c.blue },
    MasonHighlightSecondary = { fg = c.blue },
    MasonMuted = { fg = c.muted },
    MasonMutedBlock = { fg = c.bg, bg = c.muted },
    MasonMutedBlockBold = { fg = c.bg, bg = c.muted, bold = true },
    MasonNormal = { fg = c.fg, bg = c.bg },

    -- DAP (debugging)
    DapBreakpoint = { fg = c.red },
    DapBreakpointCondition = { fg = c.yellow },
    DapBreakpointRejected = { fg = c.muted },
    DapLogPoint = { fg = c.blue },
    DapStopped = { fg = c.green },
    DapStoppedLine = { bg = c.surface },
    DapUIBreakpointsCurrentLine = { fg = c.accent, bold = true },
    DapUIBreakpointsDisabledLine = { fg = c.muted },
    DapUIBreakpointsInfo = { fg = c.blue },
    DapUIBreakpointsLine = { fg = c.accent },
    DapUIBreakpointsPath = { fg = c.cyan },
    DapUICurrentFrameName = { fg = c.accent, bold = true },
    DapUIDecoration = { fg = c.accent },
    DapUIFloatBorder = { fg = c.border },
    DapUILineNumber = { fg = c.accent },
    DapUIModifiedValue = { fg = c.yellow, bold = true },
    DapUINormal = { fg = c.fg, bg = c.bg },
    DapUIPlayPause = { fg = c.green },
    DapUIPlayPauseNC = { fg = c.green },
    DapUIRestart = { fg = c.green },
    DapUIRestartNC = { fg = c.green },
    DapUIScope = { fg = c.cyan },
    DapUISource = { fg = c.magenta },
    DapUIStepBack = { fg = c.blue },
    DapUIStepBackNC = { fg = c.blue },
    DapUIStepInto = { fg = c.blue },
    DapUIStepIntoNC = { fg = c.blue },
    DapUIStepOut = { fg = c.blue },
    DapUIStepOutNC = { fg = c.blue },
    DapUIStepOver = { fg = c.blue },
    DapUIStepOverNC = { fg = c.blue },
    DapUIStop = { fg = c.red },
    DapUIStopNC = { fg = c.red },
    DapUIThread = { fg = c.green },
    DapUIType = { fg = c.yellow },
    DapUIValue = { fg = c.fg },
    DapUIVariable = { fg = c.fg },
    DapUIWatchesEmpty = { fg = c.muted },
    DapUIWatchesError = { fg = c.red },
    DapUIWatchesValue = { fg = c.green },

    -- Gitsigns (extended)
    GitSignsAddLn = { bg = c.green },
    GitSignsAddNr = { fg = c.green },
    GitSignsChangeLn = { bg = c.yellow },
    GitSignsChangeNr = { fg = c.yellow },
    GitSignsDeleteLn = { bg = c.red },
    GitSignsDeleteNr = { fg = c.red },
    GitSignsCurrentLineBlame = { fg = c.muted, italic = true },
    GitSignsAddInline = { bg = c.green },
    GitSignsChangeInline = { bg = c.yellow },
    GitSignsDeleteInline = { bg = c.red },
    GitSignsAddPreview = { fg = c.green },
    GitSignsDeletePreview = { fg = c.red },

    -- vim-gitgutter (older git plugin, still popular)
    GitGutterAdd = { fg = c.green },
    GitGutterChange = { fg = c.yellow },
    GitGutterDelete = { fg = c.red },

    -- Trouble.nvim
    TroubleCount = { fg = c.magenta, bg = c.surface },
    TroubleNormal = { fg = c.fg, bg = c.bg },
    TroubleNormalNC = { fg = c.fg, bg = c.bg },
    TroublePos = { fg = c.muted },
    TroublePreview = { bg = c.surface },
    TroubleSource = { fg = c.muted },
    TroubleText = { fg = c.fg },
    TroubleIndent = { fg = c.border },
    TroubleIndentFoldClosed = { fg = c.border },
    TroubleIndentFoldOpen = { fg = c.border },
    TroubleIndentLast = { fg = c.border },
    TroubleIndentMiddle = { fg = c.border },
    TroubleIndentTop = { fg = c.border },
    TroubleIndentWs = { fg = c.border },

    -- Neo-tree
    NeoTreeNormal = { fg = c.fg, bg = c.bg },
    NeoTreeNormalNC = { fg = c.fg, bg = c.bg },
    NeoTreeDimText = { fg = c.muted },
    NeoTreeFileName = { fg = c.fg },
    NeoTreeGitAdded = { fg = c.green },
    NeoTreeGitConflict = { fg = c.red, bold = true },
    NeoTreeGitDeleted = { fg = c.red },
    NeoTreeGitIgnored = { fg = c.muted },
    NeoTreeGitModified = { fg = c.yellow },
    NeoTreeGitUnstaged = { fg = c.yellow },
    NeoTreeGitUntracked = { fg = c.cyan },
    NeoTreeGitStaged = { fg = c.green },
    NeoTreeIndentMarker = { fg = c.border },
    NeoTreeRootName = { fg = c.accent, bold = true },
    NeoTreeTitleBar = { fg = c.bg, bg = c.accent },
    NeoTreeFloatBorder = { fg = c.border },
    NeoTreeFloatTitle = { fg = c.accent },
    NeoTreeTabActive = { fg = c.fg, bg = c.bg, bold = true },
    NeoTreeTabInactive = { fg = c.muted, bg = c.surface },
    NeoTreeTabSeparatorActive = { fg = c.accent, bg = c.bg },
    NeoTreeTabSeparatorInactive = { fg = c.border, bg = c.surface },
    NeoTreeWinSeparator = { fg = c.border },

    -- LSP Semantic tokens
    ["@lsp.type.boolean"] = { link = "@boolean" },
    ["@lsp.type.builtinType"] = { link = "@type.builtin" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.deriveHelper"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.escapeSequence"] = { link = "@string.escape" },
    ["@lsp.type.formatSpecifier"] = { link = "@markup.list" },
    ["@lsp.type.generic"] = { link = "@variable" },
    ["@lsp.type.interface"] = { fg = c.cyan },
    ["@lsp.type.keyword"] = { link = "@keyword" },
    ["@lsp.type.lifetime"] = { link = "@keyword.storage" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.namespace.python"] = { link = "@variable" },
    ["@lsp.type.number"] = { link = "@number" },
    ["@lsp.type.operator"] = { link = "@operator" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.selfKeyword"] = { link = "@variable.builtin" },
    ["@lsp.type.selfTypeKeyword"] = { link = "@variable.builtin" },
    ["@lsp.type.string"] = { link = "@string" },
    ["@lsp.type.typeAlias"] = { link = "@type.definition" },
    ["@lsp.type.unresolvedReference"] = { undercurl = true, sp = c.red },
    ["@lsp.type.variable"] = {},
    ["@lsp.type.class"] = { link = "Type" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.macro"] = { link = "Macro" },
    ["@lsp.type.method"] = { link = "Function" },
    ["@lsp.type.struct"] = { link = "Structure" },
    ["@lsp.type.type"] = { link = "Type" },
    ["@lsp.type.typeParameter"] = { link = "Typedef" },
    ["@lsp.mod.deprecated"] = { strikethrough = true },
    ["@lsp.mod.readonly"] = { italic = true },
    ["@lsp.typemod.class.defaultLibrary"] = { link = "@type.builtin" },
    ["@lsp.typemod.enum.defaultLibrary"] = { link = "@type.builtin" },
    ["@lsp.typemod.enumMember.defaultLibrary"] = { link = "@constant.builtin" },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.keyword.async"] = { link = "@keyword.coroutine" },
    ["@lsp.typemod.keyword.injected"] = { link = "@keyword" },
    ["@lsp.typemod.macro.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.method.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.operator.injected"] = { link = "@operator" },
    ["@lsp.typemod.string.injected"] = { link = "@string" },
    ["@lsp.typemod.struct.defaultLibrary"] = { link = "@type.builtin" },
    ["@lsp.typemod.type.defaultLibrary"] = { fg = c.cyan },
    ["@lsp.typemod.typeAlias.defaultLibrary"] = { fg = c.cyan },
    ["@lsp.typemod.variable.callable"] = { link = "@function" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.variable.injected"] = { link = "@variable" },
    ["@lsp.typemod.variable.static"] = { link = "@constant" },

    -- Avante (AI)
    AvanteTitle = { fg = c.bg, bg = c.accent, bold = true },
    AvanteReversedTitle = { fg = c.accent },
    AvanteSubtitle = { fg = c.bg, bg = c.blue },
    AvanteReversedSubtitle = { fg = c.blue },
    AvanteThirdTitle = { fg = c.bg, bg = c.yellow },
    AvanteReversedThirdTitle = { fg = c.yellow },
    AvanteConflictCurrent = { bg = c.green },
    AvanteConflictIncoming = { bg = c.blue },
    AvanteConflictCurrentLabel = { fg = c.bg, bg = c.green },
    AvanteConflictIncomingLabel = { fg = c.bg, bg = c.blue },
    AvantePopupHint = { fg = c.muted },
    AvanteInlineHint = { fg = c.muted },

    -- vim-illuminate
    IlluminatedWordText = { bg = c.surface },
    IlluminatedWordRead = { bg = c.surface },
    IlluminatedWordWrite = { bg = c.surface },
    illuminatedWord = { bg = c.surface },
    illuminatedCurWord = { bg = c.surface },

    -- fzf-lua
    FzfLuaNormal = { fg = c.fg, bg = c.surface },
    FzfLuaBorder = { fg = c.border, bg = c.surface },
    FzfLuaTitle = { fg = c.accent, bg = c.surface },
    FzfLuaPreviewTitle = { fg = c.accent, bg = c.surface },
    FzfLuaCursor = { link = "IncSearch" },
    FzfLuaDirPart = { fg = c.muted },
    FzfLuaFilePart = { link = "FzfLuaFzfNormal" },
    FzfLuaFzfCursorLine = { link = "Visual" },
    FzfLuaFzfNormal = { fg = c.fg },
    FzfLuaFzfPointer = { fg = c.magenta },
    FzfLuaFzfSeparator = { fg = c.yellow, bg = c.surface },
    FzfLuaHeaderBind = { link = "@punctuation.special" },
    FzfLuaHeaderText = { link = "Title" },
    FzfLuaPath = { link = "Directory" },

    -- Neogit
    NeogitBranch = { fg = c.magenta },
    NeogitRemote = { fg = c.magenta },
    NeogitHunkHeader = { fg = c.fg, bg = c.surface },
    NeogitHunkHeaderHighlight = { fg = c.blue, bg = c.surface },
    NeogitDiffContextHighlight = { fg = c.fg, bg = c.surface },
    NeogitDiffDeleteHighlight = { fg = c.red },
    NeogitDiffAddHighlight = { fg = c.green },

    -- Copilot
    CopilotAnnotation = { fg = c.muted },
    CopilotSuggestion = { fg = c.muted },

    -- Leap
    LeapMatch = { fg = c.fg, bg = c.magenta, bold = true },
    LeapLabel = { fg = c.magenta, bold = true },
    LeapBackdrop = { fg = c.muted },

    -- nvim-navic
    NavicSeparator = { fg = c.fg },
    NavicText = { fg = c.fg },
    NavicIconsFile = { fg = c.fg },
    NavicIconsModule = { fg = c.blue },
    NavicIconsNamespace = { fg = c.blue },
    NavicIconsPackage = { fg = c.blue },
    NavicIconsClass = { fg = c.yellow },
    NavicIconsMethod = { fg = c.blue },
    NavicIconsProperty = { fg = c.green },
    NavicIconsField = { fg = c.green },
    NavicIconsConstructor = { fg = c.magenta },
    NavicIconsEnum = { fg = c.yellow },
    NavicIconsInterface = { fg = c.cyan },
    NavicIconsFunction = { fg = c.blue },
    NavicIconsVariable = { fg = c.fg },
    NavicIconsConstant = { fg = c.cyan },
    NavicIconsString = { fg = c.green },
    NavicIconsNumber = { fg = c.yellow },
    NavicIconsBoolean = { fg = c.yellow },
    NavicIconsArray = { fg = c.fg },
    NavicIconsObject = { fg = c.cyan },
    NavicIconsKey = { fg = c.green },
    NavicIconsNull = { fg = c.cyan },
    NavicIconsEnumMember = { fg = c.cyan },
    NavicIconsStruct = { fg = c.yellow },
    NavicIconsEvent = { fg = c.magenta },
    NavicIconsOperator = { fg = c.fg },
    NavicIconsTypeParameter = { fg = c.yellow },

    -- LspKind (completion icons)
    LspKindArray = { link = "@punctuation.bracket" },
    LspKindBoolean = { link = "@boolean" },
    LspKindClass = { link = "@type" },
    LspKindColor = { link = "Special" },
    LspKindConstant = { link = "@constant" },
    LspKindConstructor = { link = "@constructor" },
    LspKindEnum = { link = "@lsp.type.enum" },
    LspKindEnumMember = { link = "@lsp.type.enumMember" },
    LspKindEvent = { link = "Special" },
    LspKindField = { link = "@variable.member" },
    LspKindFile = { link = "Normal" },
    LspKindFolder = { link = "Directory" },
    LspKindFunction = { link = "@function" },
    LspKindInterface = { link = "@lsp.type.interface" },
    LspKindKey = { link = "@variable.member" },
    LspKindKeyword = { link = "@lsp.type.keyword" },
    LspKindMethod = { link = "@function.method" },
    LspKindModule = { link = "@module" },
    LspKindNamespace = { link = "@module" },
    LspKindNull = { link = "@constant.builtin" },
    LspKindNumber = { link = "@number" },
    LspKindObject = { link = "@constant" },
    LspKindOperator = { link = "@operator" },
    LspKindPackage = { link = "@module" },
    LspKindProperty = { link = "@property" },
    LspKindReference = { link = "@markup.link" },
    LspKindSnippet = { link = "Conceal" },
    LspKindString = { link = "@string" },
    LspKindStruct = { link = "@lsp.type.struct" },
    LspKindUnit = { link = "@lsp.type.struct" },
    LspKindText = { link = "@markup" },
    LspKindTypeParameter = { link = "@lsp.type.typeParameter" },
    LspKindVariable = { link = "@variable" },
    LspKindValue = { link = "@string" },

    -- render-markdown
    RenderMarkdownBullet = { fg = c.yellow },
    RenderMarkdownCode = { bg = c.surface },
    RenderMarkdownDash = { fg = c.yellow },
    RenderMarkdownTableHead = { fg = c.red },
    RenderMarkdownTableRow = { fg = c.yellow },
    RenderMarkdownCodeInline = { link = "@markup.raw.markdown_inline" },
    RenderMarkdownH1Bg = { bg = c.surface },
    RenderMarkdownH1Fg = { fg = c.magenta, bold = true },
    RenderMarkdownH2Bg = { bg = c.surface },
    RenderMarkdownH2Fg = { fg = c.blue, bold = true },
    RenderMarkdownH3Bg = { bg = c.surface },
    RenderMarkdownH3Fg = { fg = c.green, bold = true },
    RenderMarkdownH4Bg = { bg = c.surface },
    RenderMarkdownH4Fg = { fg = c.yellow, bold = true },
    RenderMarkdownH5Bg = { bg = c.surface },
    RenderMarkdownH5Fg = { fg = c.cyan, bold = true },
    RenderMarkdownH6Bg = { bg = c.surface },
    RenderMarkdownH6Fg = { fg = c.red, bold = true },

    -- headlines.nvim
    CodeBlock = { bg = c.surface },
    Headline = { link = "Headline1" },
    Headline1 = { bg = c.surface },
    Headline2 = { bg = c.surface },
    Headline3 = { bg = c.surface },
    Headline4 = { bg = c.surface },
    Headline5 = { bg = c.surface },
    Headline6 = { bg = c.surface },

    -- yanky.nvim
    YankyPut = { link = "Search" },
    YankyYanked = { link = "IncSearch" },

    -- treesitter-context
    TreesitterContext = { bg = c.surface },
    TreesitterContextLineNumber = { fg = c.muted, bg = c.surface },
    TreesitterContextBottom = { underline = true, sp = c.border },

    -- Neotest
    NeotestAdapterName = { fg = c.magenta, bold = true },
    NeotestBorder = { fg = c.blue },
    NeotestDir = { fg = c.blue },
    NeotestExpandMarker = { fg = c.muted },
    NeotestFailed = { fg = c.red },
    NeotestFile = { fg = c.cyan },
    NeotestFocused = { fg = c.yellow },
    NeotestIndent = { fg = c.muted },
    NeotestMarked = { fg = c.blue },
    NeotestNamespace = { fg = c.green },
    NeotestPassed = { fg = c.green },
    NeotestRunning = { fg = c.yellow },
    NeotestSkipped = { fg = c.blue },
    NeotestTarget = { fg = c.blue },
    NeotestTest = { fg = c.fg },
    NeotestWinSelect = { fg = c.blue },

    -- Rainbow Delimiters
    RainbowDelimiterRed = { fg = c.red },
    RainbowDelimiterOrange = { fg = c.yellow },
    RainbowDelimiterYellow = { fg = c.yellow },
    RainbowDelimiterGreen = { fg = c.green },
    RainbowDelimiterBlue = { fg = c.blue },
    RainbowDelimiterViolet = { fg = c.magenta },
    RainbowDelimiterCyan = { fg = c.cyan },

    -- Hop.nvim
    HopNextKey = { fg = c.magenta, bold = true },
    HopNextKey1 = { fg = c.blue, bold = true },
    HopNextKey2 = { fg = c.blue },
    HopUnmatched = { fg = c.muted },

    -- Alpha.nvim
    AlphaShortcut = { fg = c.yellow },
    AlphaHeader = { fg = c.blue },
    AlphaHeaderLabel = { fg = c.yellow },
    AlphaFooter = { fg = c.accent },
    AlphaButtons = { fg = c.cyan },

    -- Lazy.nvim extended
    LazyProgressDone = { fg = c.magenta, bold = true },
    LazyProgressTodo = { fg = c.muted, bold = true },

    -- Notify extended
    NotifyBackground = { fg = c.fg, bg = c.bg },
    NotifyDEBUGBody = { fg = c.fg },
    NotifyDEBUGBorder = { fg = c.muted },
    NotifyDEBUGIcon = { fg = c.muted },
    NotifyDEBUGTitle = { fg = c.muted },
    NotifyTRACEBody = { fg = c.fg },
    NotifyTRACEBorder = { fg = c.magenta },
    NotifyTRACEIcon = { fg = c.magenta },
    NotifyTRACETitle = { fg = c.magenta },
    NotifyERRORBody = { fg = c.fg },
    NotifyWARNBody = { fg = c.fg },
    NotifyINFOBody = { fg = c.fg },

    -- Snacks extended
    SnacksNotifierBorderDebug = { fg = c.muted },
    SnacksNotifierBorderError = { fg = c.red },
    SnacksNotifierBorderInfo = { fg = c.blue },
    SnacksNotifierBorderTrace = { fg = c.magenta },
    SnacksNotifierBorderWarn = { fg = c.yellow },
    SnacksNotifierTitleDebug = { fg = c.muted },
    SnacksNotifierTitleError = { fg = c.red },
    SnacksNotifierTitleInfo = { fg = c.blue },
    SnacksNotifierTitleTrace = { fg = c.magenta },
    SnacksNotifierTitleWarn = { fg = c.yellow },

    -- Mini.jump extended
    MiniJump2dDim = { link = "Comment" },

    -- Mini.starter
    MiniStarterCurrent = { nocombine = true },
    MiniStarterFooter = { fg = c.yellow, italic = true },
    MiniStarterHeader = { fg = c.blue },
    MiniStarterInactive = { fg = c.muted },
    MiniStarterItem = { fg = c.fg },
    MiniStarterItemBullet = { fg = c.border },
    MiniStarterItemPrefix = { fg = c.yellow },
    MiniStarterQuery = { fg = c.accent },
    MiniStarterSection = { fg = c.accent },

    -- Mini.tabline
    MiniTablineCurrent = { fg = c.fg, bg = c.surface },
    MiniTablineFill = { bg = c.bg },
    MiniTablineHidden = { fg = c.muted, bg = c.surface },
    MiniTablineModifiedCurrent = { fg = c.yellow, bg = c.surface },
    MiniTablineModifiedHidden = { fg = c.yellow, bg = c.surface },
    MiniTablineModifiedVisible = { fg = c.yellow, bg = c.surface },
    MiniTablineTabpagesection = { bg = c.surface },
    MiniTablineVisible = { fg = c.fg, bg = c.surface },

    -- Mini.test
    MiniTestEmphasis = { bold = true },
    MiniTestFail = { fg = c.red, bold = true },
    MiniTestPass = { fg = c.green, bold = true },

    -- Mini.trailspace
    MiniTrailspace = { bg = c.red },

    -- Mini.animate
    MiniAnimateCursor = { reverse = true, nocombine = true },
    MiniAnimateNormalFloat = { link = "NormalFloat" },

    -- Mini.clue
    MiniClueBorder = { link = "FloatBorder" },
    MiniClueDescGroup = { fg = c.yellow },
    MiniClueDescSingle = { link = "NormalFloat" },
    MiniClueNextKey = { fg = c.cyan },
    MiniClueNextKeyWithPostkeys = { fg = c.red },
    MiniClueSeparator = { fg = c.blue },
    MiniClueTitle = { link = "FloatTitle" },

    -- Mini.completion
    MiniCompletionActiveParameter = { underline = true },

    -- Mini.deps
    MiniDepsChangeAdded = { link = "diffAdded" },
    MiniDepsChangeRemoved = { link = "diffRemoved" },
    MiniDepsHint = { link = "DiagnosticHint" },
    MiniDepsInfo = { link = "DiagnosticInfo" },
    MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
    MiniDepsPlaceholder = { link = "Comment" },
    MiniDepsTitle = { link = "Title" },
    MiniDepsTitleError = { fg = c.bg, bg = c.red },
    MiniDepsTitleSame = { link = "Comment" },
    MiniDepsTitleUpdate = { fg = c.bg, bg = c.green },

    -- Mini.map
    MiniMapNormal = { link = "NormalFloat" },
    MiniMapSymbolCount = { link = "Special" },
    MiniMapSymbolLine = { link = "Title" },
    MiniMapSymbolView = { link = "Delimiter" },

    -- Mini.notify
    MiniNotifyBorder = { link = "FloatBorder" },
    MiniNotifyNormal = { link = "NormalFloat" },
    MiniNotifyTitle = { link = "FloatTitle" },

    -- Mini.operators
    MiniOperatorsExchangeFrom = { link = "IncSearch" },

    -- Scrollbar.nvim
    ScrollbarHandle = { bg = c.surface },
    ScrollbarError = { fg = c.red },
    ScrollbarErrorHandle = { fg = c.red, bg = c.surface },
    ScrollbarWarn = { fg = c.yellow },
    ScrollbarWarnHandle = { fg = c.yellow, bg = c.surface },
    ScrollbarInfo = { fg = c.blue },
    ScrollbarInfoHandle = { fg = c.blue, bg = c.surface },
    ScrollbarHint = { fg = c.cyan },
    ScrollbarHintHandle = { fg = c.cyan, bg = c.surface },
    ScrollbarSearch = { fg = c.yellow },
    ScrollbarSearchHandle = { fg = c.yellow, bg = c.surface },
    ScrollbarMisc = { fg = c.magenta },
    ScrollbarMiscHandle = { fg = c.magenta, bg = c.surface },

    -- ALE
    ALEErrorSign = { fg = c.red },
    ALEWarningSign = { fg = c.yellow },

    -- Vim-sneak
    Sneak = { fg = c.surface, bg = c.magenta },
    SneakScope = { bg = c.selection },

    -- AI completions extended
    CodeiumSuggestion = { fg = c.muted },
    SupermavenSuggestion = { fg = c.muted },

    -- IndentMini.nvim
    IndentLine = { fg = c.border, nocombine = true },
    IndentLineCurrent = { fg = c.accent, nocombine = true },

    -- nvim-cmp (popular completion plugin)
    CmpDocumentation = { fg = c.fg, bg = c.surface },
    CmpDocumentationBorder = { fg = c.border, bg = c.surface },
    CmpGhostText = { fg = c.muted },
    CmpItemAbbr = { fg = c.fg },
    CmpItemAbbrDeprecated = { fg = c.muted, strikethrough = true },
    CmpItemAbbrMatch = { fg = c.accent, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.accent, bold = true },
    CmpItemKindDefault = { fg = c.muted },
    CmpItemMenu = { fg = c.muted },
    CmpItemKindText = { fg = c.fg },
    CmpItemKindMethod = { fg = c.blue },
    CmpItemKindFunction = { fg = c.blue },
    CmpItemKindConstructor = { fg = c.magenta },
    CmpItemKindField = { fg = c.cyan },
    CmpItemKindVariable = { fg = c.fg },
    CmpItemKindClass = { fg = c.yellow },
    CmpItemKindInterface = { fg = c.yellow },
    CmpItemKindModule = { fg = c.blue },
    CmpItemKindProperty = { fg = c.cyan },
    CmpItemKindUnit = { fg = c.yellow },
    CmpItemKindValue = { fg = c.cyan },
    CmpItemKindEnum = { fg = c.yellow },
    CmpItemKindKeyword = { fg = c.magenta },
    CmpItemKindSnippet = { fg = c.green },
    CmpItemKindColor = { fg = c.green },
    CmpItemKindFile = { fg = c.fg },
    CmpItemKindReference = { fg = c.cyan },
    CmpItemKindFolder = { fg = c.blue },
    CmpItemKindEnumMember = { fg = c.cyan },
    CmpItemKindConstant = { fg = c.cyan },
    CmpItemKindStruct = { fg = c.yellow },
    CmpItemKindEvent = { fg = c.magenta },
    CmpItemKindOperator = { fg = c.fg },
    CmpItemKindTypeParameter = { fg = c.yellow },

    -- Noice extended
    NoiceCmdlineIconInput = { fg = c.yellow },
    NoiceCmdlineIconLua = { fg = c.blue },
    NoiceCmdlinePopupBorderInput = { fg = c.yellow },
    NoiceCmdlinePopupBorderLua = { fg = c.blue },
    NoiceCmdlinePopupTitleInput = { fg = c.yellow },
    NoiceCmdlinePopupTitleLua = { fg = c.blue },

    -- Snacks extended
    SnacksProfilerIconInfo = { fg = c.blue },
    SnacksProfilerBadgeInfo = { fg = c.bg, bg = c.blue },
    SnacksProfilerIconTrace = { fg = c.magenta },
    SnacksProfilerBadgeTrace = { fg = c.bg, bg = c.magenta },
    SnacksZenIcon = { fg = c.accent },
    SnacksInputIcon = { fg = c.accent },
    SnacksInputBorder = { fg = c.accent },
    SnacksInputTitle = { fg = c.accent },
    SnacksPickerBoxTitle = { fg = c.accent, bold = true },
    SnacksPickerPickWinCurrent = { fg = c.accent, bold = true },
    SnacksPickerPickWin = { fg = c.blue },
    SnacksGitLabel = { fg = c.yellow },
    SnacksGitDiffHeader = { fg = c.blue },
    SnacksIndent1 = { fg = c.red },
    SnacksIndent2 = { fg = c.yellow },
    SnacksIndent3 = { fg = c.green },
    SnacksIndent4 = { fg = c.cyan },
    SnacksIndent5 = { fg = c.blue },
    SnacksIndent6 = { fg = c.magenta },
    SnacksIndent7 = { fg = c.red },
    SnacksIndent8 = { fg = c.yellow },
    SnacksFooterKey = { fg = c.yellow },
    SnacksFooterDesc = { fg = c.fg },

    -- GlyphPalette (icon colors)
    GlyphPalette1 = { fg = c.red },
    GlyphPalette2 = { fg = c.green },
    GlyphPalette3 = { fg = c.yellow },
    GlyphPalette4 = { fg = c.blue },
    GlyphPalette6 = { fg = c.cyan },
    GlyphPalette7 = { fg = c.fg },
    GlyphPalette9 = { fg = c.red },

    -- GrugFar (search/replace)
    GrugFarHelpHeader = { fg = c.muted },
    GrugFarHelpHeaderKey = { fg = c.cyan },
    GrugFarInputLabel = { fg = c.accent },
    GrugFarInputPlaceholder = { fg = c.muted },
    GrugFarResultsChangeIndicator = { fg = c.cyan },
    GrugFarResultsHeader = { fg = c.accent },
    GrugFarResultsLineColumn = { fg = c.muted },
    GrugFarResultsLineNo = { fg = c.muted },
    GrugFarResultsMatch = { fg = c.bg, bg = c.red },
    GrugFarResultsStats = { fg = c.blue },

    -- Octo.nvim (GitHub integration)
    OctoDetailsLabel = { fg = c.cyan, bold = true },
    OctoDetailsValue = { link = "@variable.member" },
    OctoDirty = { fg = c.yellow, bold = true },
    OctoIssueTitle = { fg = c.magenta, bold = true },
    OctoStateChangesRequested = { fg = c.yellow },
    OctoStateClosed = { fg = c.red },
    OctoStateMerged = { fg = c.magenta },
    OctoStateOpen = { fg = c.green },
    OctoStatePending = { fg = c.yellow },
    OctoStatusColumn = { fg = c.cyan },

    -- Dashboard.nvim
    DashboardHeader = { fg = c.blue },
    DashboardFooter = { fg = c.muted },
    DashboardProjectTitle = { fg = c.cyan },
    DashboardProjectTitleIcon = { fg = c.cyan },
    DashboardProjectIcon = { fg = c.yellow },
    DashboardMruTitle = { fg = c.cyan },
    DashboardMruIcon = { fg = c.magenta },
    DashboardFiles = { fg = c.fg },
    DashboardShortCutIcon = { fg = c.magenta },
    DashboardDesc = { fg = c.cyan },
    DashboardKey = { fg = c.yellow },
    DashboardIcon = { fg = c.cyan },
    DashboardShortCut = { fg = c.cyan },

    -- VimWiki
    VimwikiLink = { fg = c.blue, underline = true },
    VimwikiHeaderChar = { fg = c.muted },
    VimwikiHR = { fg = c.yellow },
    VimwikiList = { fg = c.yellow },
    VimwikiTag = { fg = c.yellow },
    VimwikiMarkers = { fg = c.muted },
    VimwikiHeader1 = { fg = c.magenta, bold = true },
    VimwikiHeader2 = { fg = c.blue, bold = true },
    VimwikiHeader3 = { fg = c.green, bold = true },
    VimwikiHeader4 = { fg = c.yellow, bold = true },
    VimwikiHeader5 = { fg = c.cyan, bold = true },
    VimwikiHeader6 = { fg = c.red, bold = true },
    -- SnipRun virtual text (inline code output)
    SniprunVirtualTextOk = { fg = c.bg, bg = c.green, bold = true },
    SniprunVirtualTextErr = { fg = c.bg, bg = c.red, bold = true },
  }

  -- Apply highlights

  for group, opts in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, opts)
  end
end

-- Auto-apply when colorscheme is loaded
M.setup()

return M
