[font]
size = 18

[font.bold]
family = "Menlo"
style = "Bold"

[font.normal]
family = "Menlo"
style = "Regular"

[font.offset]
x = 0
y = 0

[colors.primary]
background = "#22272e"
foreground = "#adbac7"

[colors.cursor]
text = "#22272e"
cursor = "#adbac7"

[colors.normal]
black = "#545d68"
red = "#f47067"
green = "#57ab5a"
yellow = "#c69026"
blue = "#539bf5"
magenta = "#b083f0"
cyan = "#39c5cf"
white = "#909dab"

[colors.bright]
black = "#636e7b"
red = "#ff938a"
green = "#6bc46d"
yellow = "#daaa3f"
blue = "#6cb6ff"
magenta = "#dcbdfb"
cyan = "#56d4dd"
white = "#cdd9e5"
