[font]
size = 18

[font.bold]
family = "MesloLGL Nerd Font"
style = "Bold"

[font.normal]
family = "MesloLGL Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[colors.primary]
background = "#e8e9ec"
foreground = "#33374c"

[colors.cursor]
text = "#e8e9ec"
cursor = "#33374c"

[colors.normal]
black = "#dcdfe7"
red = "#cc517a"
green = "#668e3d"
yellow = "#c57339"
blue = "#2d539e"
magenta = "#7759b4"
cyan = "#3f83a6"
white = "#33374c"

[colors.bright]
black = "#8389a3"
red = "#cc3768"
green = "#598030"
yellow = "#b6662d"
blue = "#22478e"
magenta = "#6845ad"
cyan = "#327698"
white = "#262a3f"
