[font]
size = 18

[font.bold]
family = "Menlo"
style = "Bold"

[font.normal]
family = "Menlo"
style = "Regular"

[font.offset]
x = 0
y = 0

[colors.primary]
background = "#000000"
foreground = "#00ffff"

[colors.cursor]
text = "#000000"
cursor = "#00ffff"

[colors.normal]
black = "#000000"
red = "#ff0000"
green = "#00ff00"
yellow = "#ffff00"
blue = "#61afef"
magenta = "#ff00ff"
cyan = "#00ffff"
white = "#ffffff"

[colors.bright]
black = "#808080"
red = "#ff8080"
green = "#80ff80"
yellow = "#ffff80"
blue = "#82aaff"
magenta = "#ff80ff"
cyan = "#80ffff"
white = "#ffffff"
