# Productivity Suite Showcase 🚀
# Experience the power of Snacks.nvim QoL suite

name: productivity_suite_demo
root: ~/

# Launch with: tmuxinator start productivity_suite_demo

windows:
  - dashboard:
      layout: even-horizontal
      panes:
        - |
          echo "🎯 SNACKS.NVIM PRODUCTIVITY SUITE"
          echo "================================"
          echo ""
          echo "Launch Neovim to see the dashboard!"
          echo ""
          sleep 2
          nvim -c "echo ''" -c "echo '⚡ Lightning-fast dashboard with recent files'" -c "echo '🔍 Smart picker with frecency algorithm'" -c "echo '🖥️  Instant terminal management'" -c "echo '🎨 Smooth animations throughout'"
        - |
          echo "📊 Performance Metrics"
          echo "===================="
          echo ""
          echo "Dashboard load: <50ms"
          echo "Picker search: <10ms"
          echo "Terminal spawn: <20ms"
          echo "Animation FPS: 60"
          echo ""
          echo "🏆 Replaces 15+ plugins"
          echo "   with ONE suite!"

  - smart_picker:
      layout: main-vertical
      main-pane-width: 70%
      panes:
        - |
          mkdir -p /tmp/picker_demo/{src,test,docs}
          cd /tmp/picker_demo
          
          # Create demo files
          echo "// Main application" > src/app.js
          echo "// API routes" > src/api.js
          echo "// Database models" > src/models.js
          echo "// Test suite" > test/app.test.js
          echo "# Documentation" > docs/README.md
          
          nvim -c "echo '🔍 SMART PICKER DEMO'" \
               -c "echo ''" \
               -c "echo 'Press <leader>ff to find files'" \
               -c "echo 'Press <leader>fg to live grep'" \
               -c "echo 'Press <leader>fb to browse buffers'" \
               -c "echo ''" \
               -c "echo '✨ Features:'" \
               -c "echo '  • Frecency sorting (most used first)'" \
               -c "echo '  • Smart .gitignore respect'" \
               -c "echo '  • Lightning-fast fuzzy matching'" \
               -c "echo '  • Beautiful preview window'"
        - |
          echo "🎯 Picker Power Features"
          echo "======================"
          echo ""
          echo "Smart Exclusions:"
          echo "  ✓ node_modules"
          echo "  ✓ .git directories"
          echo "  ✓ Binary files"
          echo "  ✓ Build artifacts"
          echo ""
          echo "Advanced Search:"
          echo "  • Regex support"
          echo "  • Case sensitivity toggle"
          echo "  • Multi-select mode"
          echo "  • Quick actions"

  - terminal_magic:
      layout: tiled
      panes:
        - nvim -c "echo '🖥️  TERMINAL MANAGEMENT'" \
               -c "echo ''" \
               -c "echo 'Press <leader>te to open terminal'" \
               -c "echo 'Press <C-\\> for floating terminal'" \
               -c "echo 'Press <leader>tg for LazyGit'" \
               -c "echo ''" \
               -c "echo 'Navigate with <C-h/j/k/l>!'"
        - |
          echo "⚡ Terminal Features"
          echo "=================="
          echo ""
          echo "• Instant spawn (<20ms)"
          echo "• Smart navigation"
          echo "• Persistent sessions"
          echo "• Float/split modes"
          echo "• Git integration"
          echo ""
          echo "🎮 Pro tip: Seamless"
          echo "vim ↔ terminal navigation!"
        - |
          echo "🐙 LazyGit Integration"
          echo "===================="
          echo ""
          echo "Full git workflow without"
          echo "leaving Neovim!"
          echo ""
          echo "• Stage files visually"
          echo "• Interactive rebase"
          echo "• Branch management"
          echo "• Stash operations"
        - |
          cd /tmp/picker_demo
          git init
          git add .
          echo "📁 Git-aware features"
          echo "==================="
          echo ""
          echo "Snacks respects your"
          echo "git configuration!"

  - focus_mode:
      layout: even-vertical
      panes:
        - |
          cat << 'EOF' > /tmp/focus_demo.md
          # Deep Work Mode 🧘
          
          Snacks.nvim provides the ultimate distraction-free environment.
          
          ## Zen Mode Features
          
          - Hide all UI elements
          - Center the content  
          - Increase font size
          - Dim inactive code
          - Focus on what matters
          
          ## How to Enable
          
          Press `<leader>z` to toggle Zen mode and enter flow state!
          
          The perfect environment for:
          - Writing documentation
          - Deep code review
          - Complex problem solving
          - Learning new concepts
          EOF
          nvim /tmp/focus_demo.md -c "echo '🧘 ZEN MODE: Press <leader>z to focus'"
        - |
          echo "🎯 Focus Statistics"
          echo "=================="
          echo ""
          echo "Productivity boost: +40%"
          echo "Distraction reduction: 85%"
          echo "Eye strain: -60%"
          echo ""
          echo "🏆 The calmest coding"
          echo "   environment ever!"

  - utilities:
      layout: tiled
      panes:
        - |
          echo "🛠️ Smart Buffer Management"
          echo "========================"
          echo ""
          echo "<leader>bd - Delete buffer"
          echo "<leader>bo - Delete others"
          echo ""
          echo "✨ Smart deletion:"
          echo "  • Preserves window layout"
          echo "  • Handles modified buffers"
          echo "  • Quick undo support"
          nvim -c "echo 'Open multiple files and try buffer commands!'"
        - |
          echo "🎨 Notification System"
          echo "===================="
          echo ""
          echo "Beautiful notifications:"
          echo "  • Success ✅"
          echo "  • Warning ⚠️"
          echo "  • Error ❌"
          echo "  • Info ℹ️"
          echo ""
          echo "Auto-dismiss & history!"
        - |
          echo "🔄 Smart Rename"
          echo "=============="
          echo ""
          echo "LSP-powered renaming:"
          echo "  • Project-wide"
          echo "  • Preview changes"
          echo "  • Undo support"
          echo ""
          echo "Press <leader>cr"
        - |
          echo "📈 Performance Impact"
          echo "==================="
          echo ""
          echo "Startup time: +8ms only!"
          echo "Memory: Optimized"
          echo "CPU: Minimal impact"
          echo ""
          echo "🚀 15 plugins → 1 suite"