#!/usr/bin/env bash
# Generate complete ~/.config/wezterm/wezterm.lua with theme colors inlined
# This is the primary WezTerm config location (checked before ~/.wezterm.lua)

set -euo pipefail

THEME="${1:-tokyonight_storm}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE="$SCRIPT_DIR/wezterm-template.lua"
THEME_FILE="$SCRIPT_DIR/themes/${THEME}.lua"
# Output to wezterm.lua in the same directory (which is symlinked to ~/.config/wezterm/)
OUTPUT="$SCRIPT_DIR/wezterm.lua"

# Ensure config directory exists
mkdir -p "$(dirname "$OUTPUT")"

if [[ ! -f "$THEME_FILE" ]]; then
  echo "Error: Theme file not found: $THEME_FILE" >&2
  exit 1
fi

if [[ ! -f "$TEMPLATE" ]]; then
  echo "Error: Template file not found: $TEMPLATE" >&2
  exit 1
fi

# Extract the colors table from theme file (everything between M.colors = { and the final })
# We need to convert M.colors to config.colors
extract_colors() {
  local in_colors=0
  local brace_count=0

  while IFS= read -r line; do
    # Start of colors table
    if [[ "$line" =~ ^M\.colors[[:space:]]*=[[:space:]]*\{ ]]; then
      echo "config.colors = {"
      in_colors=1
      brace_count=1
      continue
    fi

    if [[ $in_colors -eq 1 ]]; then
      # Count braces to know when we're done
      local open_braces="${line//[^\{]/}"
      local close_braces="${line//[^\}]/}"
      brace_count=$((brace_count + ${#open_braces} - ${#close_braces}))

      echo "$line"

      if [[ $brace_count -eq 0 ]]; then
        break
      fi
    fi
  done <"$THEME_FILE"
}

# Generate the complete config file
{
  # Header
  cat <<'HEADER'
-- WezTerm Configuration - GPU-accelerated terminal emulator
-- AUTO-GENERATED by generate-config.sh - DO NOT EDIT DIRECTLY
-- Edit src/wezterm/wezterm.lua instead, then run: theme <name>

local wezterm = require("wezterm")
local config = wezterm.config_builder()

HEADER

  # Font configuration (copy from template, skip the color loading section)
  awk '
    /^-- FONT CONFIGURATION/,/^-- COLOR SCHEME/ {
      if (/^-- COLOR SCHEME/) next
      print
    }
  ' "$TEMPLATE"

  # Color scheme section header
  echo ""
  echo "-- COLOR SCHEME - $THEME (inlined for reliable live reload)"
  echo ""

  # Extract and insert colors
  extract_colors

  echo ""
  echo "config.bold_brightens_ansi_colors = true"
  echo ""

  # Rest of config (everything after the color loading section)
  awk '
    BEGIN { skip=0; found_window=0 }
    /^-- WINDOW CONFIGURATION/ { found_window=1 }
    found_window { print }
  ' "$TEMPLATE"

} >"$OUTPUT"

chmod 644 "$OUTPUT"
echo "Generated $OUTPUT with $THEME theme"
