[font]
size = 18

[font.bold]
family = "Menlo"
style = "Bold"

[font.normal]
family = "Menlo"
style = "Regular"

[font.offset]
x = 0
y = 0

[colors.primary]
background = "#ffffff"
foreground = "#0e1116"

[colors.cursor]
text = "#ffffff"
cursor = "#0e1116"

[colors.normal]
black = "#0e1116"
red = "#a0111f"
green = "#024c1a"
yellow = "#3f2200"
blue = "#0349b4"
magenta = "#622cbc"
cyan = "#1b7c83"
white = "#66707b"

[colors.bright]
black = "#4b535d"
red = "#86061d"
green = "#055d20"
yellow = "#4e2c00"
blue = "#1168e3"
magenta = "#844ae7"
cyan = "#3192aa"
white = "#88929d"
