# TokyoNight Day Alacritty Colors
# Official colors from https://github.com/folke/tokyonight.nvim

[colors.primary]
background = '#e1e2e7'
foreground = '#3760bf'

[colors.normal]
black = '#b4b5b9'
red = '#f52a65'
green = '#587539'
yellow = '#8c6c3e'
blue = '#2e7de9'
magenta = '#9854f1'
cyan = '#007197'
white = '#6172b0'

[colors.bright]
black = '#a1a6c5'
red = '#ff4774'
green = '#5c8524'
yellow = '#a27629'
blue = '#358aff'
magenta = '#a463ff'
cyan = '#007ea8'
white = '#3760bf'

[[colors.indexed_colors]]
index = 16
color = '#b15c00'

[[colors.indexed_colors]]
index = 17
color = '#c64343'