# TokyoNight Day theme for Alacritty

[colors.primary]
background = "#e1e2e7"
foreground = "#3760bf"

[colors.normal]
black = "#e9e9ed"
red = "#f52a65"
green = "#587539"
yellow = "#8c6c3e"
blue = "#2e7de9"
magenta = "#9854f1"
cyan = "#007197"
white = "#6172b0"

[colors.bright]
black = "#a1a6c5"
red = "#f52a65"
green = "#587539"
yellow = "#8c6c3e"
blue = "#2e7de9"
magenta = "#9854f1"
cyan = "#007197"
white = "#3760bf"

[colors.cursor]
cursor = "#3760bf"
text = "#e1e2e7"

[colors.selection]
background = "#99a7df"
text = "#3760bf"