# TokyoNight Day Alacritty Colors

[colors.primary]
background = '#e1e2e7'
foreground = '#3760bf'

[colors.normal]
black = '#a1a6c5'
red = '#f52a65'
green = '#587539'
yellow = '#8c6c3e'
blue = '#2e7de9'
magenta = '#9854f1'
cyan = '#007197'
white = '#3760bf'

[colors.bright]
black = '#8990b3'
red = '#c64343'
green = '#485e30'
yellow = '#b07c48'
blue = '#118ce1'
magenta = '#7847bd'
cyan = '#006a83'
white = '#273e89'

[[colors.indexed_colors]]
index = 16
color = '#b15c00'

[[colors.indexed_colors]]
index = 17
color = '#c64343'