[font]
size = 18

[font.bold]
family = "MesloLGL Nerd Font"
style = "Bold"

[font.normal]
family = "MesloLGL Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[colors.primary]
background = "#ffffff"
foreground = "#24292f"

[colors.cursor]
text = "#ffffff"
cursor = "#24292f"

[colors.normal]
black = "#24292f"
red = "#b35900"
green = "#0550ae"
yellow = "#4d2d00"
blue = "#0969da"
magenta = "#8250df"
cyan = "#1b7c83"
white = "#6e7781"

[colors.bright]
black = "#57606a"
red = "#8a4600"
green = "#0969da"
yellow = "#633c01"
blue = "#218bff"
magenta = "#a475f9"
cyan = "#3192aa"
white = "#8c959f"
