# Universal clangd configuration - Works on macOS and Linux
CompileFlags:
  Add: 
    - "-std=c++17"
    # Platform-specific includes will be added by clangd based on system
    # These are common paths that exist on multiple systems
    - "-I/usr/local/include"
    - "-I/usr/include"
  Remove:
    # Remove any system-specific flags that might cause issues
    - "-stdlib=libc++"

# On macOS, clangd will automatically find:
# - /opt/homebrew/include (Apple Silicon)
# - /usr/local/include (Intel)
# - SDK paths

# On Linux, clangd will automatically find:
# - /usr/include
# - /usr/local/include
# - GCC/Clang system paths

Diagnostics:
  ClangTidy:
    Add: [performance-*, modernize-*, readability-*]
    Remove: [modernize-use-trailing-return-type, readability-magic-numbers]
  UnusedIncludes: Strict

Completion:
  AllScopes: true
  DetailedLabel: true

InlayHints:
  Enabled: true
  ParameterNames: true
  DeducedTypes: true
  Designators: true
  BlockEnd: true

Index:
  Background: Build
  StandardLibrary: Yes