export PATH=$HOME/bin:/usr/local/bin:$PATH

# Ensure proper locale settings for UTF-8
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

# Zinit configuration
export ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Faster vim mode
export KEYTIMEOUT=1

# If on SSH, just use vim
if [[ $SSH_CONNECTION ]]; then
   export EDITOR='vim'
fi

export python3="/usr/local/bin/python3"

# If not on SSH, still use vim
export VISUAL=nvim
export EDITOR="$VISUAL"
. "$HOME/.cargo/env"
